"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.getModesSection = exports.getCapabilitiesSection = exports.getToolUseGuidelinesSection = exports.getMcpServersSection = exports.getSharedToolUseSection = exports.addCustomInstructions = exports.getObjectiveSection = exports.getSystemInfoSection = exports.getRulesSection = void 0;
var rules_1 = require("./rules");
Object.defineProperty(exports, "getRulesSection", { enumerable: true, get: function () { return rules_1.getRulesSection; } });
var system_info_1 = require("./system-info");
Object.defineProperty(exports, "getSystemInfoSection", { enumerable: true, get: function () { return system_info_1.getSystemInfoSection; } });
var objective_1 = require("./objective");
Object.defineProperty(exports, "getObjectiveSection", { enumerable: true, get: function () { return objective_1.getObjectiveSection; } });
var custom_instructions_1 = require("./custom-instructions");
Object.defineProperty(exports, "addCustomInstructions", { enumerable: true, get: function () { return custom_instructions_1.addCustomInstructions; } });
var tool_use_1 = require("./tool-use");
Object.defineProperty(exports, "getSharedToolUseSection", { enumerable: true, get: function () { return tool_use_1.getSharedToolUseSection; } });
var mcp_servers_1 = require("./mcp-servers");
Object.defineProperty(exports, "getMcpServersSection", { enumerable: true, get: function () { return mcp_servers_1.getMcpServersSection; } });
var tool_use_guidelines_1 = require("./tool-use-guidelines");
Object.defineProperty(exports, "getToolUseGuidelinesSection", { enumerable: true, get: function () { return tool_use_guidelines_1.getToolUseGuidelinesSection; } });
var capabilities_1 = require("./capabilities");
Object.defineProperty(exports, "getCapabilitiesSection", { enumerable: true, get: function () { return capabilities_1.getCapabilitiesSection; } });
var modes_1 = require("./modes");
Object.defineProperty(exports, "getModesSection", { enumerable: true, get: function () { return modes_1.getModesSection; } });
//# sourceMappingURL=index.js.map